en_strings = {
    'start_message': "Hello! You have been registered in our database. Send me a text, and I'll respond to it. 📝",
    'not_registered': "You are not registered. Please use /start to register. 📝",
    'processing_message': "Processing... Please wait... ⌛",
    'error_message': "An error occurred: {error}",
    'not_enough_tokens': "Not enough tokens. You can buy more using the 'Buy Tokens 💰' command.",
    'buy_tokens_prompt': "Enter the number of tokens you want to buy. 💰💰",
    'admin_cannot_buy_tokens': "Admins cannot buy tokens. 🚫",
    'token_purchase_success': "Что бы купить токены, напишите: @someUnknowmen",
    'invalid_token_quantity': "Invalid token quantity. Please enter a number. 🤷‍♂️",
    'user_banned_message': "You are banned and cannot send messages. 🚫",
    'user_ban_success': "User {username} has been banned. 🔨",
    'user_unban_success': "User {username} has been unbanned. 🛠️",
    'user_not_found': "User not found. 🕵️‍♂️",
    'invalid_user_id': "Invalid user ID. Usage: /{command} <user_id> 🤷‍♂️",
    'add_tokens_success': "Added {tokens_to_add} tokens to user {username}. 💳",
    'list_users_permission_denied': "You don't have permission to list users. 🚫",
    'add_tokens_permission_denied': "You don't have permission to add tokens. 🚫",
    'unban_user_permission_denied': "You don't have permission to unban users. 🚫",
    'check_tokens_message': "Your remaining tokens: {remaining_tokens} 💳",
    'ban_notification': "User @{username} (ID: {user_id}) has been banned due to exceeding the rate limit. 🚫",
    'token_purchase_notification': "User @{username} (ID: {user_id}) purchased {tokens_to_buy} tokens. 💰",
    'user_registration_log': "User {username} with ID {user_id} has registered and received 100 tokens on {registration_date}.",
    'user_start_log': "User {username} with ID {user_id} started the bot. 🚀"
}

# Russian language strings
ru_strings = {
    'start_message': "Привет! Вы зарегистрированы в нашей базе данных. Отправьте мне текст, и я на него отвечу. 📝",
    'not_registered': "Вы не зарегистрированы. Используйте /start для регистрации. 📝",
    'processing_message': "Обработка... Пожалуйста, подождите... ⌛",
    'error_message': "Произошла ошибка: {error}",
    'not_enough_tokens': "Недостаточно токенов. Вы можете купить больше, используя команду 'Купить токены 💰'.",
    'buy_tokens_prompt': "Введите количество токенов, которые вы хотите купить. 💰💰",
    'admin_cannot_buy_tokens': "Администраторы не могут покупать токены. 🚫",
    'token_purchase_success': "Что бы купить токены, напишите: @someUnknowmen",
    'invalid_token_quantity': "Недопустимое количество токенов. Пожалуйста, введите число. 🤷‍♂️",
    'user_banned_message': "Вы заблокированы и не можете отправлять сообщения. 🚫",
    'user_ban_success': "Пользователь {username} был заблокирован. 🔨",
    'user_unban_success': "Пользователь {username} был разблокирован. 🛠️",
    'user_not_found': "Пользователь не найден. 🕵️‍♂️",
    'invalid_user_id': "Недопустимый идентификатор пользователя. Использование: /{command} <идентификатор_пользователя> 🤷‍♂️",
    'add_tokens_success': "Добавлено {tokens_to_add} токенов пользователю {username}. 💳",
    'list_users_permission_denied': "У вас нет разрешения на просмотр пользователей. 🚫",
    'add_tokens_permission_denied': "У вас нет разрешения на добавление токенов. 🚫",
    'unban_user_permission_denied': "У вас нет разрешения на разблокировку пользователей. 🚫",
    'check_tokens_message': "Ваши оставшиеся токены: {remaining_tokens} 💳",
    'ban_notification': "Пользователь @{username} (ID: {user_id}) был заблокирован из-за превышения лимита. 🚫",
    'token_purchase_notification': "Пользователь @{username} (ID: {user_id}) купил {tokens_to_buy} токенов. 💰",
    'user_registration_log': "Пользователь {username} с ID {user_id} зарегистрирован и получил 100 токенов {registration_date}.",
    'user_start_log': "Пользователь {username} с ID {user_id} запустил бота. 🚀"
}
